### ISSUE TITLE
Breaking Change in sensor.h of esphome?

### ISSUE THREAD

**Issue by dobernoeder** [pulsar256/vindriktning_esphome#3]
I used the library with esphome 2023.3 and all worked very well.

Now I updated to 2023.4 and it looks like the functionality got broken. When I try to compile with 2023.4 I get the following error:
```
Archiving .pioenvs/bad-raumsensor/libd7c/libESPAsyncWebServer-esphome.a
In file included from src/main.cpp:67:
src/vindriktning.h:4:40: warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]
    4 |     static constexpr char *const TAG = "vindriktning";
      |                                        ^~~~~~~~~~~~~~
src/vindriktning.h: In constructor 'VindriktningSensor::VindriktningSensor(esphome::uart::UARTComponent*)':
src/vindriktning.h:14:50: error: no matching function for call to 'esphome::sensor::Sensor::Sensor(const char [11])'
   14 |         : Sensor("pm25sensor"), UARTDevice(parent) {}
      |                                                  ^
In file included from src/esphome/components/adc/adc_sensor.h:6,
                 from src/esphome.h:3,
                 from src/main.cpp:3:
src/esphome/components/sensor/sensor.h:59:12: note: candidate: 'esphome::sensor::Sensor::Sensor()'
   59 |   explicit Sensor();
      |            ^~~~~~
src/esphome/components/sensor/sensor.h:59:12: note:   candidate expects 0 arguments, 1 provided
src/esphome/components/sensor/sensor.h:57:7: note: candidate: 'esphome::sensor::Sensor::Sensor(const esphome::sensor::Sensor&)'
   57 | class Sensor : public EntityBase {
      |       ^~~~~~
src/esphome/components/sensor/sensor.h:57:7: note:   no known conversion for argument 1 from 'const char [11]' to 'const esphome::sensor::Sensor&'
src/esphome/components/sensor/sensor.h:57:7: note: candidate: 'esphome::sensor::Sensor::Sensor(esphome::sensor::Sensor&&)'
src/esphome/components/sensor/sensor.h:57:7: note:   no known conversion for argument 1 from 'const char [11]' to 'esphome::sensor::Sensor&&'
```

Atter some research I found out that there had been a change in sensor.h of esphome project, see line 57 in https://github.com/esphome/esphome/commit/535003014b121b17fad17878979a0e63e3b3de1a

It looks like the constructor was changed and a second parameter was introduced. So the current call is no longer working. Unfortunately, this is the farest I can get with C++ KnowHow.

Can you please have a look? How can this problem be fixed?

**Comment by pulsar256** [comment]
looks like an easy one. Updated the master (https://github.com/pulsar256/vindriktning_esphome/commit/ad93e7281aaf285da9228044b0b284165f318f1f) - please give it a try. Could reproduce and compile with the fix over here.

**Comment by dobernoeder** [comment]
Works fine. Great :-)
Thank you.
